### ISSUE TITLE
Uncaught TypeError: a is not a constructor

### ISSUE THREAD

**Issue by faultables** [Simperium/simperium-js#23]
First I initialize my Simperium

```
var simperium = new Simperium('<my_app_id>', {
  token: '<taken_from_auth>'
})
```

So based on tutorial, I choose a bucket

```
var bucket = simperium.bucket('bucketname');
```

![image](https://user-images.githubusercontent.com/6561394/41155918-fa06edae-6b49-11e8-820a-9e4ce370ff39.png)

And then...

![image](https://user-images.githubusercontent.com/6561394/41155942-15837ad4-6b4a-11e8-9141-cba0d8c092b4.png)

I realize that this code was last updated 4/5 years ago, any info for this project? Is this project is dead? thanks

**Comment by bayareacoder** [comment]
We use similar code in a Backbone project and it works. Maybe an import gone wrong? We have been using Simperium for a few years and it works reliably. Since this startup was acquired by Automatic they seem to be not promoting it anymore for external use much. There is no active ecosystem.

**Comment by carlelieser** [comment]
I don't know if this will help anyone, but this seems to be a problem with how simperium handles making a new instance of itself with new credentials. I noticed this when trying to sign into a different account in my Node.js app, it would give me this exact error.

What fixed it for me was adding the script before creating the new instance and then removing the script after the user logged out.
