### ISSUE TITLE
jsondiff.js apply_list_transform shifting indexes does not account for cumulative inserts or deletes

### ISSUE THREAD

**Issue by mackross** [Simperium/simperium-js#5]
For source `['A', 'B', 'C', 'D']`

transforming `diff_a = {1 : { 'o' : '+', 'v' : 'E'}}`
onto `diff_b = {1 : { 'o' : '+', 'v' : 'F'}, 2 : { 'o' : '+', 'v' : 'G'}}`

should shift index 1 in `diff_a` to 3 not 2.

transforming `diff_a = { 2: { 'o' : '+', 'v' : 'E'}}`
onto `diff_b = {1 : { 'o' : '-'}, 2 : { 'o' : '-'}}`

should shift index 2 in `diff_a` to 1 not 0.

**Comment by chengfred** [comment]
Fixed in Simperium/jsondiff@390733f
